config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :collections, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :artworks, only: [:index, :show, :create, :new, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :collection
  has_one_attached :photo
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :artworks
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :collection
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_artwork, only: [:show, :edit, :update, :destroy]
    
    def index
      @artworks = Artwork.all
    end

    def show
    end

    def new
      @artwork = Artwork.new
    end

    def edit
    end 

    def update
      @artwork.update(artwork_params)
      redirect_to artworks_path
    end

    def create
      @artwork = Artwork.new(artwork_params)

      if @artwork.save
        redirect_to artworks_path
      else
        render :new
      end
    end

    def destroy
      @artwork.destroy
      redirect_to artworks_path
    end

    private

    def artwork_params
      params.require(:artwork).permit(:name, :description, :medium, :size, :collection_id, :photo, :featured)
    end

    def set_artwork
      @artwork = Artwork.find(params[:id])
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_collection, only: [:show, :edit, :update, :destroy]

    def index
      @collections = Collection.all
    end

    def show
    end

    def new
      @collection = Collection.new
    end
    
    def edit
    end

    def update
      @collection.update(collection_params)
      redirect_to collections_path
    end

    def create
      @collection = Collection.new(collection_params)

      if @collection.save
        redirect_to collections_path
      else
        render :new
      end
    end

    def destroy
      @collection.destroy
      redirect_to collections_path
    end

    private

    def collection_params
      params.require(:collection).permit(:name, :description)
    end

    def set_collection
      @collection = Collection.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @artworks = Artwork.where(featured: "true")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_form.html.erb
<%= simple_form_for(@artwork) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :collection %>
    <%= f.input :medium %>
    <%= f.input :size %>
    <%= f.input :featured %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<%= render 'form', artwork: @artwork %>

app/views/artworks/index.html.erb
<h1>All artwork</h1>
<%= link_to "new artwork", new_artwork_path %>
<br>
<br>
<br>
<div></div>
<% @artworks.each do |art| %>
<div class="indexCard">
<%= cl_image_tag art.photo.key, height: 400 if art.photo.attached? %>
<%= art.name %>
<br>
<%= art.collection.name %>
<% if user_signed_in? %>
<%= link_to edit_artwork_path(art.id) do %>
<button class="btn btn-primary mx-1">edit</button>
<% end %>
<%= link_to artwork_path(art.id), method: :delete, data: { confirm: 'Are you sure?'} do %>
<button class="btn btn-primary mx-1">delete</button>
<% end %>
<% end %>
</div>
<% end %>

app/views/artworks/new.html.erb
<%= render 'form', artwork: @artwork %>

app/views/artworks/show.html.erb
<h1>hello</h1>
<%= @artwork.name %>
<%= @artwork.collection.name %>
<%= cl_image_tag @artwork.photo.key, height: 600 %>

app/views/collections/_form.html.erb
<%= simple_form_for(@collection) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<%= render 'form', collection:  @collection %>

app/views/collections/index.html.erb
<h1>All collections</h1>
<%= link_to "new collection", new_collection_path %>
<br>
<br>
<br>
<br>


<% @collections.each do |coll| %>
<div class="indexCard">
<%= link_to coll.name, collection_path(coll.id) %>
<br>
<%= link_to edit_collection_path(coll.id) do %>
<button class="btn btn-primary mx-1">edit</button>
<% end %>

<%= link_to collection_path(coll.id), method: :delete, data: { confirm: 'Are you sure?'} do %>
<button class="btn btn-primary mx-1">delete</button>
<% end %>
</div>
<% end %>

app/views/collections/new.html.erb
<%= render 'form' %>

app/views/collections/show.html.erb
<div class="wrapper">
<%= @collection.name %>
<% @collection.artworks.each do |art| %>
<div class="indexCard">

<%= cl_image_tag art.photo.key, height: 400 if art.photo.attached? %>

<%= art.name %>
</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmmaChambersArt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="wrapper">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div id="carouselExampleIndicators" class="carousel carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @artworks.count.times do %>
      <% counter = 0 %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<% counter %>">
      <% counter += 1 %>
    <% end %>
  </ol>
  <div class="carousel-inner">
  <% @artworks.each_with_index do |art,i|%>
  <div class="carousel-item <%= "active " if i==0 %>">
    <div class="image-container center">
    <%= cl_image_tag art.photo.key, class: "center" if art.photo.attached? %>
    </div>
     <div class="carousel-caption">
        <div class="left">
          <h1><%= art.name %></h1>
          <div class="subtitle">
          <h2 class="subtitle"><%= art.medium %></h2>
          <i class="fas fa-circle fa-xs"></i>
          <h2 class="subtitle"><%= art.size %></h2>
          </div>
          <h3><%= art.description %></h3>
        </div>
        <div class="right">
          <h2 class="align-right">Part of</h2>
          <h4> <%= link_to art.collection.name, collection_path(art.collection) %> </h4>
        </div>
      </div>
  </div>
  <%end%>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<% if user_signed_in? %>
<%= link_to "Artworks", artworks_path %>
<br>
<br>
<%= link_to "Collections", collections_path %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand title" href="/">Emma Chambers</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Gallery</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Shop</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
  </div>
</nav>